apiVersion: v1
kind: Secret
metadata:
  name: green-cloud-secrets
type: Opaque
data:
  JWT_SECRET: amV0LWxvY2FsLWpzLXRvLW5vdC11c2UtaW4tcHJvZA==
  ELECTRICITY_MAPS_API_KEY: ZGVtb2VtLWVtLWFwaS1rZXktbG9jYWw=
  VAULT_TOKEN: cm9vdA==
